# Generated by Django 5.0.2 on 2024-02-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookData",
            fields=[
                ("bookID", models.IntegerField(primary_key=True, serialize=False)),
                ("bookname", models.CharField(max_length=50)),
                ("authorname", models.CharField(max_length=50)),
                ("dopublication", models.DateField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
